title: "Jordan Liu"
author: "Jordan Liu"
description: "University of Oxford"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "/resume.pdf", title: "CV", sidebaricon: home}
  - {title: "Thesis", url: "https://docs.google.com/document/d/1HXXoG7gAqiLI4wJ99RNM-c-mFOGUfARf"}
  - {title: "Options pricer", url: "https://github.com/JordanLiu112/My_option_pricing_program"}
  - {title: "Work blog", file: "blog.md"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:jordanliu112@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/JordanLiu112"}
  

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
